// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/[...catchall].tsx";
import * as $2 from "./routes/api/autocomplete.tsx";
import * as $3 from "./routes/api/newsletter.tsx";
import * as $4 from "./routes/api/searchseller.tsx";
import * as $5 from "./routes/api/shippingsimulation.tsx";
import * as $6 from "./routes/styles.css.ts";
import * as $$0 from "./islands/AddToCartButton.tsx";
import * as $$1 from "./islands/Cart.tsx";
import * as $$2 from "./islands/Faq.tsx";
import * as $$3 from "./islands/HeaderButton.tsx";
import * as $$4 from "./islands/HeaderSearchbar.tsx";
import * as $$5 from "./islands/NavigatorShare.tsx";
import * as $$6 from "./islands/Newsletter.tsx";
import * as $$7 from "./islands/OutOfStock.tsx";
import * as $$8 from "./islands/Overlay.tsx";
import * as $$9 from "./islands/ProductCardButton.tsx";
import * as $$10 from "./islands/ProductDetails.tsx";
import * as $$11 from "./islands/ProductGallery.tsx";
import * as $$12 from "./islands/ProductImageZoom.tsx";
import * as $$13 from "./islands/SearchControls.tsx";
import * as $$14 from "./islands/ServiceMenu.tsx";
import * as $$15 from "./islands/ShippingSimulation.tsx";
import * as $$16 from "./islands/SliderJS.tsx";
import * as $$17 from "./islands/TalkToUsForm.tsx";
import * as $$18 from "./islands/WishlistButton.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/[...catchall].tsx": $1,
    "./routes/api/autocomplete.tsx": $2,
    "./routes/api/newsletter.tsx": $3,
    "./routes/api/searchseller.tsx": $4,
    "./routes/api/shippingsimulation.tsx": $5,
    "./routes/styles.css.ts": $6,
  },
  islands: {
    "./islands/AddToCartButton.tsx": $$0,
    "./islands/Cart.tsx": $$1,
    "./islands/Faq.tsx": $$2,
    "./islands/HeaderButton.tsx": $$3,
    "./islands/HeaderSearchbar.tsx": $$4,
    "./islands/NavigatorShare.tsx": $$5,
    "./islands/Newsletter.tsx": $$6,
    "./islands/OutOfStock.tsx": $$7,
    "./islands/Overlay.tsx": $$8,
    "./islands/ProductCardButton.tsx": $$9,
    "./islands/ProductDetails.tsx": $$10,
    "./islands/ProductGallery.tsx": $$11,
    "./islands/ProductImageZoom.tsx": $$12,
    "./islands/SearchControls.tsx": $$13,
    "./islands/ServiceMenu.tsx": $$14,
    "./islands/ShippingSimulation.tsx": $$15,
    "./islands/SliderJS.tsx": $$16,
    "./islands/TalkToUsForm.tsx": $$17,
    "./islands/WishlistButton.tsx": $$18,
  },
  baseUrl: import.meta.url,
};

export default manifest;
