// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/plp.ts";
import * as $$$$0 from "./routes/api/autocomplete.tsx";
import * as $$$$1 from "./routes/api/newsletter.tsx";
import * as $$$$2 from "./routes/api/searchseller.tsx";
import * as $$$$3 from "./routes/api/shippingsimulation.tsx";
import * as $$$$4 from "./routes/api/[...catchall].tsx";
import * as $$$$5 from "./routes/styles.css.ts";
import * as $$$$6 from "./routes/_app.tsx";
import * as $$$$$0 from "./islands/AddToCartButton.tsx";
import * as $$$$$1 from "./islands/Faq.tsx";
import * as $$$$$2 from "./islands/HeaderButton.tsx";
import * as $$$$$3 from "./islands/HeaderModals.tsx";
import * as $$$$$4 from "./islands/HeaderSearchbar.tsx";
import * as $$$$$5 from "./islands/Menu.tsx";
import * as $$$$$6 from "./islands/NavigatorShare.tsx";
import * as $$$$$7 from "./islands/NavItem.tsx";
import * as $$$$$8 from "./islands/Newsletter.tsx";
import * as $$$$$9 from "./islands/OutOfStock.tsx";
import * as $$$$$10 from "./islands/Overlay.tsx";
import * as $$$$$11 from "./islands/ProductCard.tsx";
import * as $$$$$12 from "./islands/ProductGallery.tsx";
import * as $$$$$13 from "./islands/ProductImageZoom.tsx";
import * as $$$$$14 from "./islands/SearchControls.tsx";
import * as $$$$$15 from "./islands/ServiceMenu.tsx";
import * as $$$$$16 from "./islands/ShippingSimulation.tsx";
import * as $$$$$17 from "./islands/SliderJS.tsx";
import * as $$$$$18 from "./islands/TalkToUsForm.tsx";
import * as $$$$$19 from "./islands/WishlistButton.tsx";
import * as $$$$$$$$0 from "./sections/BannerAustral.tsx";
import * as $$$$$$$$1 from "./sections/BannerGrid.tsx";
import * as $$$$$$$$2 from "./sections/BannerPLP.tsx";
import * as $$$$$$$$3 from "./sections/BreadcrumbInstitutional.tsx";
import * as $$$$$$$$4 from "./sections/Card.tsx";
import * as $$$$$$$$5 from "./sections/CardPlusShelf.tsx";
import * as $$$$$$$$6 from "./sections/CardsCarousel.tsx";
import * as $$$$$$$$7 from "./sections/Carousel.tsx";
import * as $$$$$$$$8 from "./sections/CookieConsent.tsx";
import * as $$$$$$$$9 from "./sections/DesignSystem.tsx";
import * as $$$$$$$$10 from "./sections/Faq.tsx";
import * as $$$$$$$$11 from "./sections/Features.tsx";
import * as $$$$$$$$12 from "./sections/Footer.tsx";
import * as $$$$$$$$13 from "./sections/Header.tsx";
import * as $$$$$$$$14 from "./sections/HeadingSearchResult.tsx";
import * as $$$$$$$$15 from "./sections/Highlights.tsx";
import * as $$$$$$$$16 from "./sections/Instafeed.tsx";
import * as $$$$$$$$17 from "./sections/InstitutionalHeading.tsx";
import * as $$$$$$$$18 from "./sections/LinkTree.tsx";
import * as $$$$$$$$19 from "./sections/LookingWhereChange.tsx";
import * as $$$$$$$$20 from "./sections/Magazine.tsx";
import * as $$$$$$$$21 from "./sections/MyAccount.tsx";
import * as $$$$$$$$22 from "./sections/OurStores.tsx";
import * as $$$$$$$$23 from "./sections/ProductDetails.tsx";
import * as $$$$$$$$24 from "./sections/ProductShelf.tsx";
import * as $$$$$$$$25 from "./sections/SaleExpress.tsx";
import * as $$$$$$$$26 from "./sections/SearchResult.tsx";
import * as $$$$$$$$27 from "./sections/SeoText.tsx";
import * as $$$$$$$$28 from "./sections/TalkToUsForm.tsx";
import * as $$$$$$$$29 from "./sections/TextInstitutional.tsx";
import * as $$$$$$$$30 from "./sections/WhatsApp.tsx";
import * as $$$$$$$$31 from "./sections/WishlistGallery.tsx";
import { DecoManifest } from "$live/types.ts";

const manifest = {
  "loaders": {
    "deco-sites/australroupas/loaders/plp.ts": $$$0,
  },
  "routes": {
    "./routes/_app.tsx": $$$$6,
    "./routes/api/[...catchall].tsx": $$$$4,
    "./routes/api/autocomplete.tsx": $$$$0,
    "./routes/api/newsletter.tsx": $$$$1,
    "./routes/api/searchseller.tsx": $$$$2,
    "./routes/api/shippingsimulation.tsx": $$$$3,
    "./routes/styles.css.ts": $$$$5,
  },
  "islands": {
    "./islands/AddToCartButton.tsx": $$$$$0,
    "./islands/Faq.tsx": $$$$$1,
    "./islands/HeaderButton.tsx": $$$$$2,
    "./islands/HeaderModals.tsx": $$$$$3,
    "./islands/HeaderSearchbar.tsx": $$$$$4,
    "./islands/Menu.tsx": $$$$$5,
    "./islands/NavigatorShare.tsx": $$$$$6,
    "./islands/NavItem.tsx": $$$$$7,
    "./islands/Newsletter.tsx": $$$$$8,
    "./islands/OutOfStock.tsx": $$$$$9,
    "./islands/Overlay.tsx": $$$$$10,
    "./islands/ProductCard.tsx": $$$$$11,
    "./islands/ProductGallery.tsx": $$$$$12,
    "./islands/ProductImageZoom.tsx": $$$$$13,
    "./islands/SearchControls.tsx": $$$$$14,
    "./islands/ServiceMenu.tsx": $$$$$15,
    "./islands/ShippingSimulation.tsx": $$$$$16,
    "./islands/SliderJS.tsx": $$$$$17,
    "./islands/TalkToUsForm.tsx": $$$$$18,
    "./islands/WishlistButton.tsx": $$$$$19,
  },
  "sections": {
    "deco-sites/australroupas/sections/BannerAustral.tsx": $$$$$$$$0,
    "deco-sites/australroupas/sections/BannerGrid.tsx": $$$$$$$$1,
    "deco-sites/australroupas/sections/BannerPLP.tsx": $$$$$$$$2,
    "deco-sites/australroupas/sections/BreadcrumbInstitutional.tsx": $$$$$$$$3,
    "deco-sites/australroupas/sections/Card.tsx": $$$$$$$$4,
    "deco-sites/australroupas/sections/CardPlusShelf.tsx": $$$$$$$$5,
    "deco-sites/australroupas/sections/CardsCarousel.tsx": $$$$$$$$6,
    "deco-sites/australroupas/sections/Carousel.tsx": $$$$$$$$7,
    "deco-sites/australroupas/sections/CookieConsent.tsx": $$$$$$$$8,
    "deco-sites/australroupas/sections/DesignSystem.tsx": $$$$$$$$9,
    "deco-sites/australroupas/sections/Faq.tsx": $$$$$$$$10,
    "deco-sites/australroupas/sections/Features.tsx": $$$$$$$$11,
    "deco-sites/australroupas/sections/Footer.tsx": $$$$$$$$12,
    "deco-sites/australroupas/sections/Header.tsx": $$$$$$$$13,
    "deco-sites/australroupas/sections/HeadingSearchResult.tsx": $$$$$$$$14,
    "deco-sites/australroupas/sections/Highlights.tsx": $$$$$$$$15,
    "deco-sites/australroupas/sections/Instafeed.tsx": $$$$$$$$16,
    "deco-sites/australroupas/sections/InstitutionalHeading.tsx": $$$$$$$$17,
    "deco-sites/australroupas/sections/LinkTree.tsx": $$$$$$$$18,
    "deco-sites/australroupas/sections/LookingWhereChange.tsx": $$$$$$$$19,
    "deco-sites/australroupas/sections/Magazine.tsx": $$$$$$$$20,
    "deco-sites/australroupas/sections/MyAccount.tsx": $$$$$$$$21,
    "deco-sites/australroupas/sections/OurStores.tsx": $$$$$$$$22,
    "deco-sites/australroupas/sections/ProductDetails.tsx": $$$$$$$$23,
    "deco-sites/australroupas/sections/ProductShelf.tsx": $$$$$$$$24,
    "deco-sites/australroupas/sections/SaleExpress.tsx": $$$$$$$$25,
    "deco-sites/australroupas/sections/SearchResult.tsx": $$$$$$$$26,
    "deco-sites/australroupas/sections/SeoText.tsx": $$$$$$$$27,
    "deco-sites/australroupas/sections/TalkToUsForm.tsx": $$$$$$$$28,
    "deco-sites/australroupas/sections/TextInstitutional.tsx": $$$$$$$$29,
    "deco-sites/australroupas/sections/WhatsApp.tsx": $$$$$$$$30,
    "deco-sites/australroupas/sections/WishlistGallery.tsx": $$$$$$$$31,
  },
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest satisfies DecoManifest;
